server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  application:
    name:  bytedanceJavaApi
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  mail:
    host: smtp.qq.com
    port: 587
    username: 745119711@qq.com
    password: pknzzonexszpbbcf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://111.231.32.32:3306/apicat
    username: root
    password: 18263130668ojL.
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret: Todayistheday
  expiration: 86400

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.byteapimanagement.bytedancejavaapi.entity
  global-config:
    db-config:
      id-type: auto
